# Generated by Django 3.2.9 on 2022-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/%Y-%m-%d/'),
        ),
    ]
